apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-ephemeral
spec:
  selector:
    matchLabels:
      app: mysql-ephemeral
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-ephemeral
    spec:
      containers:
      - name: mysql
        image: mysql:8.0 # Or your desired MySQL image version
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: your_secure_password # Replace with a strong password or use Kubernetes Secrets
        - name: MYSQL_DATABASE
          value: mydatabase # Optional: specify a default database
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        emptyDir: {} # This defines the ephemeral storage
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-ephemeral
spec:
  selector:
    app: mysql-ephemeral
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
